"""Turn Ghostty's code point property table into the one the app's terminal measures text with.

Usage: ``python scripts/ghostty_widths.py <props.zig> <ghostty commit> > miniapp/src/terminal/widths.data.ts``

The terminal daemon's emulator is libghostty-vt, and it decides how many cells every grapheme takes.
The browser has to decide exactly the same, or a restored screen and the live one drift apart on the
first emoji: a row that is one cell longer on one side pushes everything after it along. xterm.js's
own tables disagree with Ghostty's on Indic conjuncts, zero-width space and the newer emoji, so the
app does not use them; it uses Ghostty's, carried over by this script.

``props.zig`` is the file Ghostty's build writes from ``src/unicode/props_uucode.zig`` (its
``props-unigen`` step; the output lands in the Zig cache as ``props.zig``). It is a three-stage lookup
table, and every entry is a width, whether the code point is zero-width inside a grapheme, its
grapheme break class and whether an emoji variation selector may follow it. Those four facts are all
Ghostty's printer reads, and all the app's provider reads.

The output is small on purpose: the stage-three entries as packed numbers, and one entry index per
run of code points, as base64 varints — about 7 KB, where the raw stages are 80 KB.
"""

from __future__ import annotations

import base64
import re
import sys

# The order of Ghostty's `GraphemeBreakNoControl` enum. The app's state machine names the classes by
# these positions, so this list and `BREAK` in `unicode.ts` must say the same thing.
BREAK_CLASSES = [
    "other",
    "prepend",
    "regional_indicator",
    "spacing_mark",
    "l",
    "v",
    "t",
    "lv",
    "lvt",
    "zwj",
    "zwnj",
    "extended_pictographic",
    "emoji_modifier_base",
    "emoji_modifier",
    "indic_conjunct_break_extend",
    "indic_conjunct_break_linker_extend",
    "indic_conjunct_break_linker_other",
    "indic_conjunct_break_consonant",
]

MAX_CODE_POINT = 0x10FFFF

ENTRY = re.compile(
    r"\.width= (\d+),\s*\.width_zero_in_grapheme= (true|false),\s*"
    r"\.grapheme_break= \.(\w+),\s*\.emoji_vs_base= (true|false),"
)


def stage(source: str, name: str) -> list[int]:
    match = re.search(name + r": \[\d+\]u16 = \.\{([^}]*)\}", source)
    if not match:
        raise SystemExit(f"{name} not found: is this Ghostty's generated props.zig?")
    return [int(n) for n in re.findall(r"\d+", match.group(1))]


def pack(width: str, zero: str, klass: str, vs_base: str) -> int:
    """One entry as the app reads it: width in bits 0-1, zero-in-grapheme bit 2, class bits 3-7, VS base bit 8."""
    if klass not in BREAK_CLASSES:
        raise SystemExit(f"unknown grapheme break class {klass!r}: Ghostty changed its enum, update BREAK_CLASSES and unicode.ts")
    return int(width) | (zero == "true") << 2 | BREAK_CLASSES.index(klass) << 3 | (vs_base == "true") << 8


def varint(value: int, out: bytearray) -> None:
    while True:
        low = value & 0x7F
        value >>= 7
        if value:
            out.append(low | 0x80)
        else:
            out.append(low)
            return


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    source = open(sys.argv[1], encoding="utf-8").read()
    commit = sys.argv[2]
    stage1, stage2 = stage(source, "stage1"), stage(source, "stage2")
    entries = [pack(*m) for m in ENTRY.findall(source.split("stage3", 1)[1])]
    if len(entries) > 255:
        raise SystemExit("more than 255 distinct entries: the run encoding stores one byte per run")

    runs = bytearray()
    previous, last_start, count = -1, 0, 0
    for code_point in range(MAX_CODE_POINT + 1):
        index = stage2[stage1[code_point >> 8] + (code_point & 0xFF)]
        if index != previous:
            varint(code_point - last_start, runs)
            runs.append(index)
            previous, last_start, count = index, code_point, count + 1

    print("// Generated by scripts/ghostty_widths.py from Ghostty's code point property table. Do not edit;")
    print("// regenerate it whenever the terminal daemon's Ghostty is bumped, and run the width test after.")
    print()
    print(f'export const GHOSTTY_TABLE_SOURCE = "ghostty {commit}";')
    print()
    print("/** Packed entries: width bits 0-1, zero-width-in-grapheme bit 2, break class bits 3-7, emoji VS base bit 8. */")
    print(f"export const ENTRIES: readonly number[] = [{', '.join(str(e) for e in entries)}];")
    print()
    print(f"/** {count} runs, each a varint distance from the previous run's start and one byte of entry index. */")
    print(f'export const RUNS = "{base64.b64encode(bytes(runs)).decode()}";')


if __name__ == "__main__":
    main()
