// How many cells a piece of text takes, decided the way the terminal daemon's emulator decides it.
//
// The daemon runs libghostty-vt with grapheme clustering on (mode 2027), and every snapshot it sends
// is laid out by Ghostty's rules. xterm.js has its own tables, and they disagree with Ghostty's in four
// places: Indic conjuncts (Ghostty joins them, Unicode 15.1), spacing marks, U+200B (Ghostty drops it)
// and the Unicode 13–15 emoji such as 🫠 (Ghostty gives them two cells, which is right; xterm.js gives
// one and the glyph overlaps its neighbour). One cell of disagreement shifts the rest of the row, and
// a reattached screen then no longer lines up with the one the application thinks it drew. So the
// browser does not use xterm.js's tables at all: this provider replays Ghostty's table (generated by
// `scripts/ghostty_widths.py`) and Ghostty's printer, and `unicode.test.ts` holds it to grids recorded
// from libghostty itself.
//
// Where xterm.js cannot follow, and why (each is rare, and each is covered by a test that pins it):
// - A variation selector 15 that would narrow a wide emoji: xterm.js can widen a cell it has written,
//   never narrow it, so the cluster keeps two cells where Ghostty gives one.
// - U+00AD: xterm.js drops the soft hyphen before any provider sees it; Ghostty prints it in one cell.
// - A zero-width code point that starts a row, or a join split by an escape sequence: xterm.js tells a
//   provider nothing about the cell on the left after an escape, while Ghostty reads that cell. A
//   zero-width mark is still attached to the cell on the left, so only width-changing joins (a VS16, a
//   ZWJ sequence) interrupted by an escape come out differently.

import type { IUnicodeVersionProvider, ITerminalAddon, Terminal } from "@xterm/xterm";
import { ENTRIES, RUNS } from "./widths.data";

/** The name the provider registers under; `terminal.unicode.activeVersion` is set to it. */
export const GHOSTTY_UNICODE_VERSION = "ghostty";

// Ghostty's grapheme break classes, in the order of its `GraphemeBreakNoControl` enum (the order
// `scripts/ghostty_widths.py` packs them in). Class 0, "other", needs no name: no rule tests for it.
const PREPEND = 1;
const REGIONAL_INDICATOR = 2;
const SPACING_MARK = 3;
const L = 4;
const V = 5;
const T = 6;
const LV = 7;
const LVT = 8;
const ZWJ = 9;
const ZWNJ = 10;
const EXTENDED_PICTOGRAPHIC = 11;
const EMOJI_MODIFIER_BASE = 12;
const EMOJI_MODIFIER = 13;
const INCB_EXTEND = 14;
const INCB_LINKER_EXTEND = 15;
const INCB_LINKER_OTHER = 16;
const INCB_CONSONANT = 17;

const width = (entry: number) => entry & 3;
const zeroInGrapheme = (entry: number) => (entry & 4) !== 0;
const breakClass = (entry: number) => (entry >> 3) & 31;
const emojiVsBase = (entry: number) => (entry & 256) !== 0;

// The table: every BMP code point indexed directly (64 KB), the rest found by binary search over the
// runs. Built on first use, because the module is loaded with xterm and most pages never open one.
let bmp: Uint8Array | null = null;
let astralStarts: Uint32Array = new Uint32Array(0);
let astralValues: Uint8Array = new Uint8Array(0);

function build(): Uint8Array {
  const bytes = Uint8Array.from(atob(RUNS), (c) => c.charCodeAt(0));
  const starts: number[] = [];
  const values: number[] = [];
  let position = 0;
  let start = 0;
  while (position < bytes.length) {
    let delta = 0;
    let shift = 0;
    for (;;) {
      const byte = bytes[position++];
      delta += (byte & 0x7f) * 2 ** shift;
      shift += 7;
      if (byte < 0x80) break;
    }
    start += delta;
    starts.push(start);
    values.push(bytes[position++]);
  }
  const table = new Uint8Array(0x10000);
  let firstAstral = starts.length;
  for (let i = 0; i < starts.length; i++) {
    const end = i + 1 < starts.length ? starts[i + 1] : 0x110000;
    if (starts[i] >= 0x10000) {
      firstAstral = i;
      break;
    }
    table.fill(values[i], starts[i], Math.min(end, 0x10000));
    if (end > 0x10000) {
      firstAstral = i;
      break;
    }
  }
  astralStarts = Uint32Array.from(starts.slice(firstAstral));
  astralValues = Uint8Array.from(values.slice(firstAstral));
  bmp = table;
  return table;
}

/** The index into `ENTRIES` for a code point. Anything past U+10FFFF is Ghostty's "width 1". */
function entryIndex(codepoint: number): number {
  const table = bmp ?? build();
  if (codepoint < 0x10000) return table[codepoint];
  if (codepoint > 0x10ffff) return 1;
  let lo = 0;
  let hi = astralStarts.length - 1;
  while (lo < hi) {
    const mid = (lo + hi + 1) >> 1;
    if (astralStarts[mid] <= codepoint) lo = mid;
    else hi = mid - 1;
  }
  return astralValues[lo];
}

/** Ghostty's entry for a code point: its width, zero-width-in-grapheme flag, break class and VS base flag. */
export function ghosttyEntry(codepoint: number): number {
  return ENTRIES[entryIndex(codepoint)];
}

// The grapheme break state machine: uucode's `computeGraphemeBreakNoControl`, which Ghostty's
// printer runs, carried over line by line. Its state is three bits: `after_linker` in bit 0 and the
// base (0 none, 1 extended pictographic, 2 regional indicator) in bits 1-2.
const BASE_NONE = 0;
const BASE_PICTOGRAPHIC = 1;
const BASE_REGIONAL = 2;

const isExtend = (c: number) => c === ZWNJ || c === INCB_EXTEND || c === INCB_LINKER_EXTEND;
const isPictographic = (c: number) => c === EXTENDED_PICTOGRAPHIC || c === EMOJI_MODIFIER_BASE;
const isIncbExtend = (c: number) => c === INCB_EXTEND || c === ZWJ;
const isIncbLinker = (c: number) => c === INCB_LINKER_EXTEND || c === INCB_LINKER_OTHER;
const keepsPictographic = (c: number) =>
  c === INCB_EXTEND || c === INCB_LINKER_EXTEND || c === ZWNJ || c === ZWJ || c === EXTENDED_PICTOGRAPHIC || c === EMOJI_MODIFIER_BASE || c === EMOJI_MODIFIER;

/**
 * Whether there is a grapheme boundary between two code points of the given classes, and the state
 * for the next pair. Returned packed — the boundary in bit 0, the state in bits 1-3 — because it runs
 * for every code point above U+00FF that a terminal prints.
 */
export function graphemeBreak(gb1: number, gb2: number, state: number): number {
  const afterLinker = isIncbLinker(gb1) || ((state & 1) !== 0 && isIncbExtend(gb1));
  let base = state >> 1;
  const nextLinker = afterLinker && isIncbExtend(gb2) ? 1 : 0;
  const result = (brk: boolean) => (brk ? 1 : 0) | ((nextLinker | (base << 1)) << 1);

  if (base === BASE_REGIONAL) {
    if (gb1 !== REGIONAL_INDICATOR || gb2 !== REGIONAL_INDICATOR) base = BASE_NONE;
  } else if (base === BASE_PICTOGRAPHIC) {
    if (!keepsPictographic(gb1)) base = BASE_NONE;
    if (!keepsPictographic(gb2)) base = BASE_NONE;
  }

  // GB6, GB7, GB8: Hangul syllable sequences.
  if (gb1 === L && (gb2 === L || gb2 === V || gb2 === LV || gb2 === LVT)) return result(false);
  if ((gb1 === LV || gb1 === V) && (gb2 === V || gb2 === T)) return result(false);
  if ((gb1 === LVT || gb1 === T) && gb2 === T) return result(false);
  // GB9a, GB9b.
  if (gb2 === SPACING_MARK) return result(false);
  if (gb1 === PREPEND) return result(false);
  // GB9c: InCB=Linker InCB=Extend* × InCB=Consonant.
  if (afterLinker && gb2 === INCB_CONSONANT) {
    base = BASE_NONE;
    return result(false);
  }
  // GB11: emoji ZWJ sequences, and emoji modifier sequences (UTS #51 tailoring).
  if (isPictographic(gb1)) {
    if (isExtend(gb2) || gb2 === ZWJ) {
      base = BASE_PICTOGRAPHIC;
      return result(false);
    }
    if (gb1 === EMOJI_MODIFIER_BASE && gb2 === EMOJI_MODIFIER) {
      base = BASE_PICTOGRAPHIC;
      return result(false);
    }
  } else if (base === BASE_PICTOGRAPHIC) {
    if ((isExtend(gb1) || gb1 === EMOJI_MODIFIER) && (isExtend(gb2) || gb2 === ZWJ)) return result(false);
    if (gb1 === ZWJ && isPictographic(gb2)) {
      base = BASE_NONE;
      return result(false);
    }
    base = BASE_NONE;
  }
  // GB12, GB13: regional indicators pair up.
  if (gb1 === REGIONAL_INDICATOR && gb2 === REGIONAL_INDICATOR) {
    if (base === BASE_NONE) {
      base = BASE_REGIONAL;
      return result(false);
    }
    base = BASE_NONE;
    return result(true);
  }
  // GB9.
  if (isExtend(gb2) || gb2 === ZWJ) return result(false);
  // GB999.
  return result(true);
}

// What xterm.js hands back to us as `preceding`: `state << 3 | width << 1 | joined`, where our state
// is the entry index of the code point the cluster last took (bits 0-4), the break state (bits 5-7)
// and a bit saying there is a cluster at all (bit 8). Zero — xterm.js's "nothing before this", after
// every control and escape sequence — has that bit clear.
const PRESENT = 1 << 8;

const pack = (state: number, cells: number, join: boolean) => (state << 3) | (cells << 1) | (join ? 1 : 0);

/** The xterm.js provider. Stateless: everything it needs travels in the value xterm.js hands back. */
export const ghosttyUnicode: IUnicodeVersionProvider = {
  version: GHOSTTY_UNICODE_VERSION,

  wcwidth(codepoint: number): 0 | 1 | 2 {
    if (codepoint < 0x20 || (codepoint >= 0x7f && codepoint < 0xa0)) return 0;
    if (codepoint <= 0xff) return 1;
    return width(ghosttyEntry(codepoint)) as 0 | 1 | 2;
  },

  charProperties(codepoint: number, preceding: number): number {
    const index = entryIndex(codepoint);
    // Ghostty's printer gives every Latin-1 character one cell and never joins it to the cell before
    // (its grapheme path starts above U+00FF).
    if (codepoint <= 0xff) return pack(PRESENT | index, 1, false);

    const entry = ENTRIES[index];
    const state = preceding >> 3;
    if (!(state & PRESENT)) {
      // Nothing to cluster with. A zero-width code point is still attached to the cell on the left,
      // at no width, which is where Ghostty puts a mark after an escape sequence.
      if (width(entry) === 0) return pack(0, 0, true);
      return pack(PRESENT | index, width(entry), false);
    }

    const cells = (preceding >> 1) & 3;
    const previous = ENTRIES[state & 31];
    const step = graphemeBreak(breakClass(previous), breakClass(entry), (state >> 5) & 7);
    if (step & 1) {
      // A new cluster. Ghostty drops one that would take no cells (a lone U+200B, a stray mark after
      // a break); xterm.js cannot drop it, so it rides along invisibly in the cell on the left and
      // the state stays as if it had not come.
      if (width(entry) === 0) return pack(state, cells, true);
      return pack(PRESENT | index, width(entry), false);
    }

    const next = PRESENT | index | ((step >> 1) << 5);
    if (codepoint === 0xfe0f || codepoint === 0xfe0e) {
      // A variation selector counts only after a code point that has a variation sequence; after
      // anything else Ghostty ignores it, and so does the state.
      if (!emojiVsBase(previous)) return pack(state, cells, true);
      return pack(next, codepoint === 0xfe0f ? 2 : cells, true);
    }
    return pack(next, zeroInGrapheme(entry) ? cells : 2, true);
  },
};

/** Registers the provider on a terminal and makes it the active one. Needs `allowProposedApi`. */
export class GhosttyUnicodeAddon implements ITerminalAddon {
  activate(terminal: Terminal): void {
    terminal.unicode.register(ghosttyUnicode);
    terminal.unicode.activeVersion = GHOSTTY_UNICODE_VERSION;
  }

  dispose(): void {
    /* the provider holds nothing per terminal */
  }
}
